app.frontend.url=http://localhost:5173
app.file-server.url=http://localhost:8888/uploads/

application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

logging.level.org.flywaydb=DEBUG
logging.level.com.zaxxer.hikari.HikariPool=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.com.navrotskyi.trippyapi=DEBUG